//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipboardSync.Client.Mobile.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClipboardSync.Client.Mobile.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 所有服务器均无法连接。 的本地化字符串。
        /// </summary>
        public static string AllServersAreUnavailable {
            get {
                return ResourceManager.GetString("AllServersAreUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除所有 的本地化字符串。
        /// </summary>
        public static string ClearAllHistoryList {
            get {
                return ResourceManager.GetString("ClearAllHistoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剪贴板 的本地化字符串。
        /// </summary>
        public static string Clipboard {
            get {
                return ResourceManager.GetString("Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剪贴板历史记录容量更改为  的本地化字符串。
        /// </summary>
        public static string ClipboardHistoryCapacityChanged2 {
            get {
                return ResourceManager.GetString("ClipboardHistoryCapacityChanged2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已连接至 的本地化字符串。
        /// </summary>
        public static string Connected2 {
            get {
                return ResourceManager.GetString("Connected2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已复制到剪贴板。 的本地化字符串。
        /// </summary>
        public static string CopyComplete {
            get {
                return ResourceManager.GetString("CopyComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详细 的本地化字符串。
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入整数数字 的本地化字符串。
        /// </summary>
        public static string EnterIntegerPlaceholder {
            get {
                return ResourceManager.GetString("EnterIntegerPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剪贴板历史记录容量 的本地化字符串。
        /// </summary>
        public static string HistoryListCapacity {
            get {
                return ResourceManager.GetString("HistoryListCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只会影响本设备。输入非正数表示不限制大小。 的本地化字符串。
        /// </summary>
        public static string HistoryListCapacityDescription {
            get {
                return ResourceManager.GetString("HistoryListCapacityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主页 的本地化字符串。
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在这里输入什么…… 的本地化字符串。
        /// </summary>
        public static string InputSthHere {
            get {
                return ResourceManager.GetString("InputSthHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English（英文） 的本地化字符串。
        /// </summary>
        public static string Lang_en {
            get {
                return ResourceManager.GetString("Lang_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简体中文 的本地化字符串。
        /// </summary>
        public static string Lang_zh_cn {
            get {
                return ResourceManager.GetString("Lang_zh_cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 (Language) 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重启应用生效。
        ///Restart the application to apply the language change. 的本地化字符串。
        /// </summary>
        public static string LanguageDescription {
            get {
                return ResourceManager.GetString("LanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不是有效的Url。 的本地化字符串。
        /// </summary>
        public static string NotAValidUrl {
            get {
                return ResourceManager.GetString("NotAValidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 。 的本地化字符串。
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 固定 的本地化字符串。
        /// </summary>
        public static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已固定 的本地化字符串。
        /// </summary>
        public static string Pinned {
            get {
                return ResourceManager.GetString("Pinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存并重新连接 的本地化字符串。
        /// </summary>
        public static string SaveAndReconnect {
            get {
                return ResourceManager.GetString("SaveAndReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送 的本地化字符串。
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送剪贴板的内容 的本地化字符串。
        /// </summary>
        public static string SendClipboardText {
            get {
                return ResourceManager.GetString("SendClipboardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送失败。可能是尚未连接到服务器，也可能是尝试发送空文本。 的本地化字符串。
        /// </summary>
        public static string SendFail {
            get {
                return ResourceManager.GetString("SendFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已发送。 的本地化字符串。
        /// </summary>
        public static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器地址 的本地化字符串。
        /// </summary>
        public static string ServerAddr {
            get {
                return ResourceManager.GetString("ServerAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式为 IP:port，多个地址分号隔开，如：
        ///192.168.1.2:6789; 10.20.31.54:2333
        ///当指定多个地址时，优先尝试排在前面的。 的本地化字符串。
        /// </summary>
        public static string ServerAddrDescription {
            get {
                return ResourceManager.GetString("ServerAddrDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你需要输入至少一个服务器地址！！！ 的本地化字符串。
        /// </summary>
        public static string ServerAddrPlaceholder {
            get {
                return ResourceManager.GetString("ServerAddrPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器历史记录缓存容量 的本地化字符串。
        /// </summary>
        public static string ServerCacheCapacity {
            get {
                return ResourceManager.GetString("ServerCacheCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入非正数表示不限制大小。 的本地化字符串。
        /// </summary>
        public static string ServerCacheCapacityDescription {
            get {
                return ResourceManager.GetString("ServerCacheCapacityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试连接到 的本地化字符串。
        /// </summary>
        public static string Try2Connect2 {
            get {
                return ResourceManager.GetString("Try2Connect2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无限 的本地化字符串。
        /// </summary>
        public static string Unlimited {
            get {
                return ResourceManager.GetString("Unlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消固定 的本地化字符串。
        /// </summary>
        public static string Unpin {
            get {
                return ResourceManager.GetString("Unpin", resourceCulture);
            }
        }
    }
}
