//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClipboardSync.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClipboardSync.Common.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 所有服务器均无法连接。 的本地化字符串。
        /// </summary>
        public static string AllServersAreUnavailable {
            get {
                return ResourceManager.GetString("AllServersAreUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剪贴板历史记录容量更改为  的本地化字符串。
        /// </summary>
        public static string ClipboardHistoryCapacityChanged2 {
            get {
                return ResourceManager.GetString("ClipboardHistoryCapacityChanged2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ， 的本地化字符串。
        /// </summary>
        public static string Comma {
            get {
                return ResourceManager.GetString("Comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接尝试被中止。 的本地化字符串。
        /// </summary>
        public static string ConnectAborted {
            get {
                return ResourceManager.GetString("ConnectAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已连接至 的本地化字符串。
        /// </summary>
        public static string Connected2 {
            get {
                return ResourceManager.GetString("Connected2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法连接到 的本地化字符串。
        /// </summary>
        public static string Failed2Connect2 {
            get {
                return ResourceManager.GetString("Failed2Connect2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未设置服务器地址，无法连接 的本地化字符串。
        /// </summary>
        public static string NoServerAddr {
            get {
                return ResourceManager.GetString("NoServerAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未连接 的本地化字符串。
        /// </summary>
        public static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 。 的本地化字符串。
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已发送。 的本地化字符串。
        /// </summary>
        public static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器历史记录缓存容量更改为  的本地化字符串。
        /// </summary>
        public static string ServerCacheCapacityChanged2 {
            get {
                return ResourceManager.GetString("ServerCacheCapacityChanged2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试连接到 的本地化字符串。
        /// </summary>
        public static string Try2Connect2 {
            get {
                return ResourceManager.GetString("Try2Connect2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无限 的本地化字符串。
        /// </summary>
        public static string Unlimited {
            get {
                return ResourceManager.GetString("Unlimited", resourceCulture);
            }
        }
    }
}
